#!/usr/bin/env bash

set -euo pipefail

if [[ -d src/ ]]; then

  printf "Building src/\n"

  mkdir -p dst/lib/

  if [[ "${MODE:-development}" == production ]]; then

    javac src/com/mycompany/mywebappserver/MyWebAppServer.java -sourcepath src/ -cp "dst/lib/*" -d dst/lib/

  else

    javac src/com/mycompany/mywebappserver/MyWebAppServer.java -sourcepath src/ -cp "dst/lib/*" -d dst/lib/ -g
 
  fi

  jar cf dst/lib/mywebappserver.jar -C dst/lib/ com/

  rm -r dst/lib/com/

fi

printf "Done\n"

